server:
  port: 8096  
  servlet:  
    context-path: /pet  
spring:   
  application:
    name: pet-service  
  datasource: 
    url: jdbc:postgresql://localhost:5432/petBT?CreateDatabaseIfNotExist=true
    username: postgres
    password:  password@123     

    driver-class-name: org.postgresql.Driver   
  jpa:  
    hibernate:
     ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect 
        namingStrategy: org.hibernate.cfg.PhysicalNamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    
  cloud:
    discovery:
      enabled: false
      
swagger:  
  url: http://localhost:8095/pet 
  

    



