server:
  port: 8096
  servlet:
    context-path: /pet  
spring:  
  application:
    name: pet-service  
  datasource: 
    url: jdbc:postgresql://britistelecom.postgres.database.azure.com:5432/petBT  
    username:  rohith
    password: password@123   
#    initialization-mode: always
    driver-class-name: org.postgresql.Driver    
  jpa:
    hibernate:
     ddl-auto: update  
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQL95Dialect 
        namingStrategy: org.hibernate.cfg.PhysicalNamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true  
    show-sql: true
    
  cloud:
    discovery:
      enabled: true  
         
swagger:
  url: https://petservice.dev.skillassure.com/pet

